# Generated by Django 4.2.3 on 2023-07-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payload',
        ),
    ]
